##
# SITE SETTINGS
##
title: The Shuttleworth Foundation
email: jason@shuttleworthfoundation.org
description: "We're the Shuttleworth Foundation. We provide funding for dynamic leaders who are at the forefront of social change."
baseurl: ""
url: "http://shuttleworthfoundation.org"
twitter_username: ShuttleworthFdn
github_username: jasonhudson

intake:
  open: false
  reopen: January 2017
  current: March 2017
  next: September 2017

exclude: [Makefile, README.md, vendor, Gemfile]

##
# BUILD SETTINGS
##
markdown: kramdown
permalink: pretty
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

gems:
  - jekyll-archives

##
# JEKYLL-ARCHIVES
##

jekyll-archives:
  enabled: ['year', 'tags']
  permalinks:
    year: '/thinking/:year/'
    month: '/thinking/:year/:month/'
    day: '/thinking/:year/:month/:day/'
    tag: '/thinking/tag/:name/'
    category: '/thinking/category/:name/'
  layouts:
    year: archive/year
    tag: archive/tag

##
# COLLECTIONS
##
collections:
  fellows:
    output: true
  team:
    output: true

